// Auto-generated by @commitpress/sdk — do not edit
// Run: npx commitpress generate

import { query as _query, sitemap as _sitemap, type ContentFile, type SitemapOptions, type SitemapEntry, type RichtextDoc } from '@commitpress/sdk'
import { resolve } from 'path'

const __root = resolve(process.cwd(), "")

export type IntroBlock = {
  "eyebrow": string
  "statement": string
  "body": string
  "link": { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
}
export type FaqBlock = {
  "eyebrow": string
  "heading": string
  "items": Array<{
    "question": string
    "answer": string
  }>
}
export type CtaBlock = {
  "eyebrow": string
  "heading": string
  "body": string
  "buttons"?: Array<{
    "link"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
    "style"?: "border" | "solid"
  }>
}

export interface NotesContent {
  "story"?: {
    "title"?: string
    "summary"?: string
    "category"?: string
    "date"?: string
    "cover"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string }; alt?: { "src"?: string; "mobile"?: string } }
    "body"?: RichtextDoc
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface SiteContent {
  "details": {
    "name": string
    "tagline": string
  }
  "nav": Array<{
    "href": { href: string; label?: string }
  }>
  "mobile_nav": Array<{
    "href": { href: string; label?: string }
  }>
}
export interface CollectionContent {
  "collection": {
    "eyebrow"?: string
    "title": string
    "summary"?: string
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface GalleryContent {
  "gallery": {
    "eyebrow"?: string
    "title": string
    "summary"?: string
    "gallery"?: string | { folder: string; order?: string[] }
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface HomeContent {
  "home": {
    "eyebrow"?: string
    "title": string
    "summary"?: string
    "cover"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string }; alt?: { "src"?: string; "mobile"?: string } }
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface PageContent {
  "page": {
    "eyebrow"?: string
    "title": string
    "summary"?: string
    "cover"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string }; alt?: { "src"?: string; "mobile"?: string } }
    "body"?: RichtextDoc
    "next_page"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
  }
  "blocks"?: Array<
    | { "intro": IntroBlock }
    | { "faq": FaqBlock }
    | { "cta": CtaBlock }
  >
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface RedirectContent { redirect: { destination: string; status?: '301' | '302' | '303' | '307' | '308' } }

export type ContentMap = {
  "content/collections/notes/by-the-water": NotesContent
  "content/collections/notes/into-the-green": NotesContent
  "content/collections/notes/not-yet": NotesContent
  "content/collections/notes/room-to-breathe": NotesContent
  "content/globals/site": SiteContent
  "content/pages/about": PageContent
  "content/pages/collection": CollectionContent
  "content/pages/gallery": GalleryContent
  "content/pages/images": GalleryContent
  "content/pages/index": HomeContent
  "content/pages/pages/a-quiet-corner": PageContent
  "content/pages/pages": PageContent
}

export type AnyContentFile =
  | (ContentFile<NotesContent> & { schema: "notes" })
  | (ContentFile<SiteContent> & { schema: "site" })
  | (ContentFile<CollectionContent> & { schema: "collection" })
  | (ContentFile<GalleryContent> & { schema: "gallery" })
  | (ContentFile<HomeContent> & { schema: "home" })
  | (ContentFile<PageContent> & { schema: "page" })
  | (ContentFile<RedirectContent> & { schema: "redirect" })

export function query<K extends keyof ContentMap>(slug: K, options?: import('@commitpress/sdk').QueryOptions): Promise<ContentFile<ContentMap[K]>>
export function query(slug: string, options?: import('@commitpress/sdk').QueryOptions): Promise<AnyContentFile>
export function query(slug: string, options = {}): Promise<AnyContentFile> {
  return _query(slug, __root, options) as Promise<AnyContentFile>
}
export function sitemap(options: Omit<SitemapOptions, 'root'> = {}): Promise<SitemapEntry[]> {
  return _sitemap({ ...options, root: __root })
}
export type { ContentFile }