// Auto-generated by @commitpress/sdk — do not edit
// Run: npx commitpress generate

import { query as _query, sitemap as _sitemap, type ContentFile, type SitemapOptions, type SitemapEntry, type RichtextDoc } from '@commitpress/sdk'
import { resolve } from 'path'

const __root = resolve(process.cwd(), "")

export type HeroBlock = {
  "slides": Array<{
    "line": string
    "alt": string
    "image"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string } }
  }>
}
export type PageHeaderBlock = {
  "eyebrow": string
  "heading": string
  "lead"?: string
  "alt": string
  "image"?: string | { src: string; renditions?: { "src"?: string } }
  "buttons"?: Array<{
    "link"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
  }>
}
export type IntroBlock = {
  "eyebrow": string
  "statement": string
  "body": string
  "link": { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
}
export type ServicesBlock = {
  "eyebrow": string
  "heading": string
  "note": string
  "items": Array<{
    "title": string
    "body": string
    "href": { href: string; label?: string }
    "alt": string
    "image"?: string | { src: string; renditions?: { "src"?: string } }
  }>
}
export type StepsBlock = {
  "eyebrow": string
  "heading": string
  "note": string
  "items": Array<{
    "title": string
    "body": string
  }>
}
export type PackagesBlock = {
  "eyebrow": string
  "heading": string
  "note": string
  "items": Array<{
    "name": string
    "price": string
    "body": string
    "includes": Array<{
      "item": string
    }>
    "link": { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
  }>
}
export type GalleryBlock = {
  "eyebrow": string
  "heading": string
  "items": Array<{
    "alt": string
    "image"?: string | { src: string; renditions?: { "src"?: string } }
    "span": "wide" | "tall"
    "link": { href: string; label?: string }
    "title"?: string
    "tagline"?: string
  }>
}
export type GalleryGridBlock = {
  "eyebrow": string
  "heading": string
  "note"?: string
  "gallery"?: string | { folder: string; order?: string[]; options?: Record<string, "upright" | "landscape"> }
}
export type PhotoGridBlock = {
  "eyebrow": string
  "heading": string
  "note"?: string
  "gallery"?: boolean
  "items": Array<{
    "image"?: string | { src: string; renditions?: { "src"?: string } }
    "orientation": "upright" | "landscape"
  }>
}
export type IdPhotoBlock = {
  "eyebrow": string
  "heading": string
  "body": string
  "points": Array<{
    "point": string
  }>
  "hours_heading": string
  "buttons"?: Array<{
    "link"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
  }>
}
export type BookingBlock = {
  "eyebrow": string
  "heading": string
  "body": string
  "open_days"?: Array<{
    "date": string
    "from": string
    "to": string
  }>
  "closed_days"?: Array<{
    "date": string
    "note"?: string
  }>
  "slot_minutes": string
  "lead_time_hours": string
  "horizon_days": string
  "id_types"?: Array<{
    "label": string
  }>
  "cta_label": string
  "submit_label": string
  "footnote"?: string
  "empty_note": string
  "confirm_heading": string
  "confirm_body": string
}
export type AboutBlock = {
  "eyebrow": string
  "statement": string
  "paragraphs": Array<{
    "paragraph": string
  }>
  "alt": string
  "image"?: string
}
export type FaqBlock = {
  "eyebrow": string
  "heading": string
  "items": Array<{
    "question": string
    "answer": string
  }>
}
export type ContactBlock = {
  "eyebrow": string
  "heading": string
  "body": string
  "enquiry_types": Array<{
    "label": string
  }>
  "submit_label": string
  "footnote"?: string
}
export type CtaBlock = {
  "eyebrow": string
  "heading": string
  "body": string
  "buttons"?: Array<{
    "link"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
    "style"?: "border" | "solid"
  }>
}

export interface NotesContent {
  "story"?: {
    "title"?: string
    "summary"?: string
    "category"?: string
    "date"?: string
    "cover"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string }; alt?: { "src"?: string; "mobile"?: string } }
    "body"?: RichtextDoc
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface SiteContent {
  "details": {
    "name": string
    "tagline": string
    "phone": string
    "phone_href": string
    "email": string
    "street": string
    "postal": string
    "instagram"?: string
    "facebook"?: string
  }
  "opening_hours": Array<{
    "days": string
    "hours": string
    "closed"?: boolean
  }>
  "nav": Array<{
    "href": { href: string; label?: string }
  }>
  "mobile_nav": Array<{
    "href": { href: string; label?: string }
  }>
}
export interface GalleryContent {
  "gallery"?: {
    "title"?: string
    "tagline"?: string
    "gallery"?: string | { folder: string; order?: string[]; options?: Record<string, "upright" | "landscape"> }
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface PageContent {
  "blocks": Array<
    | { "hero": HeroBlock }
    | { "page_header": PageHeaderBlock }
    | { "intro": IntroBlock }
    | { "services": ServicesBlock }
    | { "steps": StepsBlock }
    | { "packages": PackagesBlock }
    | { "gallery": GalleryBlock }
    | { "gallery_grid": GalleryGridBlock }
    | { "photo_grid": PhotoGridBlock }
    | { "id_photo": IdPhotoBlock }
    | { "booking": BookingBlock }
    | { "about": AboutBlock }
    | { "faq": FaqBlock }
    | { "contact": ContactBlock }
    | { "cta": CtaBlock }
  >
  "showcase"?: {
    "layout"?: "home" | "page" | "collection" | "images"
    "eyebrow"?: string
    "title"?: string
    "summary"?: string
    "cover"?: string | { src: string; "mobile"?: string; renditions?: { "src"?: string; "mobile"?: string }; alt?: { "src"?: string; "mobile"?: string } }
    "body"?: RichtextDoc
    "gallery"?: string | { folder: string; order?: string[] }
    "next_page"?: { type: 'internal' | 'external' | 'data'; href: string; label?: string; target?: '_blank' | '_self' }
  }
  "seo"?: {
    "title"?: string
    "description"?: string
    "social_image"?: string | { src: string; renditions?: { "src"?: string } }
    "social_title"?: string
    "social_description"?: string
    "og_type"?: "website" | "article"
    "no_index"?: boolean
    "exclude_from_sitemap"?: boolean
  }
}
export interface RedirectContent { redirect: { destination: string; status?: '301' | '302' | '303' | '307' | '308' } }

export type ContentMap = {
  "content/collections/notes/by-the-water": NotesContent
  "content/collections/notes/into-the-green": NotesContent
  "content/collections/notes/not-yet": NotesContent
  "content/collections/notes/room-to-breathe": NotesContent
  "content/globals/site": SiteContent
  "content/pages/about": PageContent
  "content/pages/collection": PageContent
  "content/pages/gallery": GalleryContent
  "content/pages/images": PageContent
  "content/pages/index": PageContent
  "content/pages/pages/a-quiet-corner": PageContent
  "content/pages/pages": PageContent
}

export type AnyContentFile =
  | (ContentFile<NotesContent> & { schema: "notes" })
  | (ContentFile<SiteContent> & { schema: "site" })
  | (ContentFile<GalleryContent> & { schema: "gallery" })
  | (ContentFile<PageContent> & { schema: "page" })
  | (ContentFile<RedirectContent> & { schema: "redirect" })

export function query<K extends keyof ContentMap>(slug: K, options?: import('@commitpress/sdk').QueryOptions): Promise<ContentFile<ContentMap[K]>>
export function query(slug: string, options?: import('@commitpress/sdk').QueryOptions): Promise<AnyContentFile>
export function query(slug: string, options = {}): Promise<AnyContentFile> {
  return _query(slug, __root, options) as Promise<AnyContentFile>
}
export function sitemap(options: Omit<SitemapOptions, 'root'> = {}): Promise<SitemapEntry[]> {
  return _sitemap({ ...options, root: __root })
}
export type { ContentFile }